# Spina manifesty. Zastosuj: kubectl apply -k deploy/k8s
# (secret.example.yaml świadomie POMINIĘTY — sekrety twórz osobno, patrz README.md)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shop-qa-ui

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: shop-qa-ui

# images:
#   - name: shop-qa-ui
#     newName: myregistry.azurecr.io/shop-qa-ui
#     newTag: "1.0.0"
