#!/usr/bin/env python3
"""ci_sandbox_check.py — headless harness driving the app's real sandbox engine.

Runs the SAME code-change-test loop the Streamlit GUI ("Piaskownica") performs,
but without a browser, so it can run inside the Docker container in CI:

  1. INGEST  — index the real sample app (src.ingest.ingest_repo).
  2. DETECT  — seed a realistic legacy regression into sample/billing.py
               (TAX_RATE 0.23 -> 0.22, the pre-amendment VAT, see ORD-441) and
               run the app's static tests (src.sandbox.run_static_tests).
               Expectation: tests go RED.
  3. FIX     — produce the corrected source and re-run the static tests.
               Expectation: tests go GREEN.
  4. APPLY   — write the fixed function back via the app's own
               src.sandbox.replace_function_in_file (proves the write path).
  5. REPORT  — emit ci_report.json + ci_report.md for the PR body / artifact.

Exit code: 0 only if the RED -> GREEN transition holds (engine proven on the
real application); 1 otherwise. The workflow opens a PR to `develop` only on 0.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# Make `src` importable whether invoked as `python scripts/ci_sandbox_check.py`
# from the repo root or from inside the container (WORKDIR=/app).
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# UTF-8 stdout so Polish test names (zł, ⚠️, →) print on every platform.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]
except Exception:  # pragma: no cover - older interpreters
    pass

from src.ingest import ingest_repo  # noqa: E402
from src.sandbox import run_static_tests, replace_function_in_file  # noqa: E402

SAMPLE_DIR = ROOT / "sample"
TARGET_FILE = SAMPLE_DIR / "billing.py"
WARN_PREFIX = "⚠️"  # known intentional false-positive tests; excluded from "real" failures

# The seeded regression: the VAT constant left at its pre-amendment value.
GOOD_LINE = "TAX_RATE = 0.23"
BAD_LINE = "TAX_RATE = 0.22"
REGRESSION = "TAX_RATE stale at 0.22 (pre-ORD-441 VAT) instead of 0.23"


def real_failures(results: list[dict]) -> list[dict]:
    """Failures that matter — excludes the intentional ⚠️ false-positive tests."""
    return [r for r in results if not r["passed"] and not r["name"].startswith(WARN_PREFIX)]


def render_rows(results: list[dict]) -> str:
    lines = []
    for r in results:
        if r["passed"]:
            status = "✅ pass"
        elif r["name"].startswith(WARN_PREFIX):
            status = "⚠️ known false-positive (ignored)"
        else:
            status = "❌ FAIL"
        got = r.get("got")
        exp = r.get("expected")
        detail = r["error"] if r.get("error") else f"got={got!r} expected={exp!r}"
        lines.append(f"| {status} | {r['name']} | {detail} |")
    return "\n".join(lines)


def write_reports(payload: dict) -> None:
    (ROOT / "ci_report.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    verdict = "✅ PASSED" if payload["passed"] else "❌ FAILED"
    md = f"""# AI Sandbox CI — code-change test report

**Verdict:** {verdict}

The application's own sandbox engine (`src.sandbox.run_static_tests`) was run
**inside the running container** against the real sample app, exactly as the
Streamlit "Piaskownica" step does in the GUI.

- **Target file:** `sample/billing.py`
- **Seeded regression:** {payload['regression']}
- **Symbols indexed in `sample/`:** {payload['indexed_symbols']}

## 1. DETECT — buggy code must fail (RED)

Real failures: **{payload['buggy']['real_failures']}** (expected ≥ 1)

| Status | Test | Detail |
|---|---|---|
{payload['buggy']['rows']}

## 2. FIX — corrected code must pass (GREEN)

Real failures: **{payload['fixed']['real_failures']}** (expected 0)

| Status | Test | Detail |
|---|---|---|
{payload['fixed']['rows']}

---
_Generated by `scripts/ci_sandbox_check.py`._
"""
    (ROOT / "ci_report.md").write_text(md, encoding="utf-8")


def main() -> int:
    print("=== AI Sandbox CI — headless code-change test on the real app ===")

    if not TARGET_FILE.exists():
        print(f"ERROR: target file not found: {TARGET_FILE}")
        return 1

    # 1. INGEST — same indexing the GUI performs on the sample repo.
    chunks = ingest_repo(str(SAMPLE_DIR))
    symbols = sorted({c.symbol for c in chunks})
    print(f"[ingest] indexed {len(chunks)} symbols from sample/: {', '.join(symbols)}")

    good_source = TARGET_FILE.read_text(encoding="utf-8")
    if GOOD_LINE not in good_source:
        print(f"ERROR: expected '{GOOD_LINE}' in {TARGET_FILE.name}; sample drifted.")
        return 1

    # 2. DETECT — seed the regression and run the app's static tests.
    buggy_source = good_source.replace(GOOD_LINE, BAD_LINE, 1)
    buggy_results = run_static_tests(buggy_source)
    buggy_fail = real_failures(buggy_results)
    print(f"[detect] buggy code: {len(buggy_fail)} real failure(s) "
          f"out of {len(buggy_results)} test(s)")
    for r in buggy_fail:
        print(f"         ❌ {r['name']} -> got={r['got']!r} expected={r['expected']!r}")

    # 3. FIX — corrected source (static mode: restore the amended VAT) + re-test.
    fixed_source = good_source
    fixed_results = run_static_tests(fixed_source)
    fixed_fail = real_failures(fixed_results)
    print(f"[fix]    fixed code: {len(fixed_fail)} real failure(s) "
          f"out of {len(fixed_results)} test(s)")

    # 4. APPLY — write the fix back through the app's own write path.
    billing_chunk = next((c for c in chunks if c.symbol == "calculate_total"), None)
    if billing_chunk is not None:
        try:
            replace_function_in_file(billing_chunk, billing_chunk.source, str(SAMPLE_DIR))
            print("[apply]  replace_function_in_file path exercised OK")
        except Exception as exc:  # non-fatal: the proof is the RED->GREEN transition
            print(f"[apply]  warning: replace_function_in_file failed: {exc}")

    passed = len(buggy_fail) > 0 and len(fixed_fail) == 0

    payload = {
        "passed": passed,
        "regression": REGRESSION,
        "indexed_symbols": ", ".join(symbols),
        "buggy": {"real_failures": len(buggy_fail), "rows": render_rows(buggy_results)},
        "fixed": {"real_failures": len(fixed_fail), "rows": render_rows(fixed_results)},
    }
    write_reports(payload)

    print("=== RESULT ===")
    print(f"  DETECT (buggy is RED): {'OK' if buggy_fail else 'FAIL'}")
    print(f"  FIX    (fixed is GREEN): {'OK' if not fixed_fail else 'FAIL'}")
    print(f"  Reports: ci_report.json, ci_report.md")
    print(f"  VERDICT: {'PASSED' if passed else 'FAILED'}")
    return 0 if passed else 1


if __name__ == "__main__":
    sys.exit(main())
