#!/usr/bin/env python3
"""ci_validate_sample.py — PR gate.

Runs the application's own static-test engine (src.sandbox.run_static_tests)
against the **committed** sample app, inside the container, exactly as the GUI
"Piaskownica" step does when the developer clicks "Uruchom testy".

This validates the code change the developer committed in step 3: the PR to
`develop` is opened only if every applicable test is green (the intentional
"⚠️" false-positive tests are excluded, matching the GUI's own logic).

Exit code: 0 if the committed sample passes, 1 otherwise.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]
except Exception:  # pragma: no cover
    pass

from src.ingest import ingest_repo  # noqa: E402
from src.sandbox import run_static_tests, STATIC_TESTS  # noqa: E402

WARN_PREFIX = "⚠️"
SAMPLE_DIR = ROOT / "sample"
NAME_TO_FN = {t["name"]: t["fn"] for t in STATIC_TESTS}


def main() -> int:
    print("=== AI Sandbox CI — validate committed sample (PR gate) ===")
    if not SAMPLE_DIR.is_dir():
        print(f"ERROR: sample dir not found: {SAMPLE_DIR}")
        return 1

    chunks = ingest_repo(str(SAMPLE_DIR))
    symbols = sorted({c.symbol for c in chunks})
    print(f"[ingest] {len(chunks)} symbols from sample/: {', '.join(symbols)}")

    # symbols actually DEFINED per file (so we don't attribute imported names,
    # e.g. orders.py imports calculate_total but does not define it).
    defined_by_file: dict[str, set[str]] = {}
    for c in chunks:
        defined_by_file.setdefault(Path(c.file_path).name, set()).add(c.symbol)

    results: list[dict] = []
    for py_file in sorted(SAMPLE_DIR.rglob("*.py")):
        defined = defined_by_file.get(py_file.name, set())
        # only run files that define at least one tested function
        if not defined.intersection(NAME_TO_FN.values()):
            continue
        source = py_file.read_text(encoding="utf-8")
        for r in run_static_tests(source):
            if NAME_TO_FN.get(r["name"]) not in defined:
                continue  # belongs to a function this file imports, not defines
            r["_file"] = py_file.name
            results.append(r)

    real_fail = [r for r in results if not r["passed"] and not r["name"].startswith(WARN_PREFIX)]
    green = sum(1 for r in results if r["passed"] or r["name"].startswith(WARN_PREFIX))

    rows = []
    for r in results:
        if r["passed"]:
            status = "✅ pass"
        elif r["name"].startswith(WARN_PREFIX):
            status = "⚠️ known false-positive (ignored)"
        else:
            status = "❌ FAIL"
        detail = r["error"] if r.get("error") else f"got={r.get('got')!r} expected={r.get('expected')!r}"
        print(f"  [{status}] ({r['_file']}) {r['name']} -> {detail}")
        rows.append(f"| {status} | `{r['_file']}` | {r['name']} | {detail} |")

    ok = len(results) > 0 and len(real_fail) == 0

    report = {
        "passed": ok,
        "tests_run": len(results),
        "green": green,
        "real_failures": len(real_fail),
        "indexed_symbols": ", ".join(symbols),
    }
    (ROOT / "ci_report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    md = f"""# AI Sandbox CI — committed sample validation

**Verdict:** {'✅ PASSED' if ok else '❌ FAILED'}

Ran the app's own `src.sandbox.run_static_tests` against the committed `sample/`
**inside the container** — the same engine the GUI "Piaskownica" step uses.

- **Symbols indexed:** {report['indexed_symbols']}
- **Tests green:** {green} / {len(results)} (real failures: {len(real_fail)})

| Status | File | Test | Detail |
|---|---|---|---|
{chr(10).join(rows)}

_Generated by `scripts/ci_validate_sample.py`._
"""
    (ROOT / "ci_report.md").write_text(md, encoding="utf-8")

    print(f"[validate] {green}/{len(results)} green; real failures={len(real_fail)}")
    print(f"VERDICT: {'PASSED' if ok else 'FAILED'}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
